// Generated by vite-plugin-generoutes, don't modify it directly.

export const routes = [
  {
    name: '__LAYOUT_DEFAULT__',
    path: '/__layout_default__',
    component: () => import('/src/layouts/default.vue'),
    children: [
      {
        name: 'NotFoundPage',
        path: '/:pathMatch(.*)*',
        component: async () => ({
          ...(await import('/src/pages/[...all].vue')).default,
          name: 'NotFoundPage',
        }),
        meta: {
          title: '页面不存在',
          icon: '404',
        },
      },
      {
        name: 'RedirectPage',
        path: '/redirect',
        redirect: '/home',
        meta: {
          title: '重定向示例',
          description: '这个页面会自动重定向到Home页面',
        },
      },
      {
        name: 'IndexPage',
        path: '/',
        component: async () => ({
          ...(await import('/src/pages/index.vue')).default,
          name: 'IndexPage',
        }),
        meta: {
          title: '首页',
          icon: 'home',
        },
      },
      {
        name: 'HomePage',
        path: '/home',
        component: async () => ({
          ...(await import('/src/pages/home.vue')).default,
          name: 'HomePage',
        }),
        meta: {
          title: 'Home页面',
          requiresAuth: false,
        },
      },
      {
        name: 'DetailPage',
        path: '/detail',
        component: async () => ({
          ...(await import('/src/pages/detail.vue')).default,
          name: 'DetailPage',
        }),
        meta: {
          title: '详情页面',
          requiresAuth: true,
        },
      },
      {
        name: 'UserDetail',
        path: '/user/:id/:name',
        component: async () => ({
          ...(await import('/src/pages/user/[id,name].vue')).default,
          name: 'UserDetail',
        }),
        meta: {
          title: '用户详情',
          icon: 'user-detail',
        },
      },
      {
        name: 'User_[...all]',
        path: '/user/:pathMatch(.*)*',
        component: async () => ({
          ...(await import('/src/pages/user/[...all].vue')).default,
          name: 'User_[...all]',
        }),
        meta: {},
      },
      {
        name: 'UserIndex',
        path: '/user',
        component: async () => ({
          ...(await import('/src/pages/user/index.vue')).default,
          name: 'UserIndex',
        }),
        meta: {
          title: '用户列表',
          icon: 'user',
        },
        children: [
          {
            name: 'UserProfile',
            path: '/user/profile',
            component: async () => ({
              ...(await import('/src/pages/user/profile.vue')).default,
              name: 'UserProfile',
            }),
            meta: {
              title: '用户资料',
              icon: 'profile',
            },
          },
        ],
      },
      {
        name: 'AdminDashboard',
        path: '/dashboard',
        component: async () => ({
          ...(await import('/src/pages/(admin)/dashboard.vue')).default,
          name: 'AdminDashboard',
        }),
        meta: {
          title: '管理面板',
          icon: 'dashboard',
          requiresAuth: true,
        },
      },
    ],
  },
]
