// Generated by vite-plugin-generoutes, don't modify it directly.

import type { RouteMeta } from 'vite-plugin-generoutes'
import type { RouteRecordRaw } from 'vue-router'

export type GeneratedRoute = RouteRecordRaw & {
  meta?: RouteMeta
  children?: GeneratedRoute[]
}

export const routes: GeneratedRoute[] = [
  {
    name: '__LAYOUT_HOME__',
    path: '/__layout_home__',
    component: () => import('/src/layouts/home.vue'),
    children: [
      {
        name: 'IndexPage',
        path: '/',
        component: async () => ({
          ...(await import('/src/pages/index.vue')).default,
          name: 'IndexPage',
        }),
        meta: {
          title: '首页',
          icon: 'home',
          layout: 'home',
        },
      },
      {
        name: 'HomePage',
        path: '/home',
        component: async () => ({
          ...(await import('/src/pages/home.vue')).default,
          name: 'HomePage',
        }),
        meta: {
          title: 'Home页面',
          requiresAuth: false,
          layout: 'home',
        },
      },
    ],
  },
  {
    name: '__LAYOUT_DEFAULT__',
    path: '/__layout_default__',
    component: () => import('/src/layouts/default.vue'),
    children: [
      {
        name: 'AboutPage',
        path: '/about',
        component: async () => ({
          ...(await import('/src/pages/about.vue')).default,
          name: 'AboutPage',
        }),
        meta: {
          title: '关于页面',
          description: '这是一个关于页面',
        },
      },
      {
        name: 'UserDetail',
        path: '/user/:id/:name',
        component: async () => ({
          ...(await import('/src/pages/user/[id,name].vue')).default,
          name: 'UserDetail',
        }),
        meta: {
          title: '用户详情',
          icon: 'user-detail',
        },
      },
      {
        name: 'UserIndex',
        path: '/user',
        component: async () => ({
          ...(await import('/src/pages/user/index.vue')).default,
          name: 'UserIndex',
        }),
        meta: {
          title: '用户列表',
          icon: 'user',
        },
        children: [
          {
            name: 'UserProfile',
            path: '/user/profile',
            component: async () => ({
              ...(await import('/src/pages/user/profile.vue')).default,
              name: 'UserProfile',
            }),
            meta: {
              title: '用户资料',
              icon: 'profile',
            },
          },
        ],
      },
      {
        name: 'AdminDashboard',
        path: '/dashboard',
        component: async () => ({
          ...(await import('/src/pages/(admin)/dashboard.vue')).default,
          name: 'AdminDashboard',
        }),
        meta: {
          title: '管理面板',
          icon: 'dashboard',
          requiresAuth: true,
        },
      },
    ],
  },
  {
    name: 'NotFoundPage',
    path: '/:pathMatch(.*)*',
    component: async () => ({
      ...(await import('/src/pages/[...all].vue')).default,
      name: 'NotFoundPage',
    }),
    meta: {
      title: '页面不存在',
      icon: '404',
      layout: false,
    },
  },
]
